name = "TopologyPreprocessing"
uuid = "f84dc87b-1198-49da-97ab-02d881fe0800"
authors = ["Emil Dmitruk"]
version = "0.1.7"

[deps]
Eirene = "9c0f25c4-2ca1-5870-89f6-52640788da1d"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Measures = "442fdcdd-2543-5da2-b0f3-8c86c306513e"
Pipe = "b98c9c47-44ae-5843-9183-064241ee97a0"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"

[compat]
julia = "1"

[extras]
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[sources.Eirene]
url = "https://github.com/henselman-petrusek/Eirene.jl#"

[targets]
test = ["Test", "SafeTestsets"]
